# Site settings
title: Derrick Blog                      #你博客的标题
SEOTitle: 齐浩的博客 | Derrick Blog       #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-homepage.jpg    #显示在首页的背景图片
email: seven_num@163.com
description: "Every failure is leading towards success."  #网站介绍
keyword: "Derrick, Derrick Blog, 齐浩的博客, SeVen7nu, 齐浩, shell, python, Linux" #关键词
url: "http://SeVen7nu.github.io"          # your host, for absolute URL # 这个就是填写你的博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/SeVen7nu/SeVen7nu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.     # 是否开启侧边栏.
sidebar-about-description: "If there is a dream,success will be sooner or later!"
sidebar-avatar: /img/avatar_Drrick.jpg   # use absolute URL, seeing it's used in both `/` and `/about/`  # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片



# SNS settings
RSS: false          
# weibo_username:     qiubaiying
github_username:    SeVen7nu
facebook_username:  DerrickQi
#jianshu_username:   e71990ada2fd
twitter_username:   DerrickQi
zhihu_username:    DerrickQi
instagram_username:    DerrickQi  



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
disqus_username: DerrickQi

Gitalk
gitalk:
 enable: true    #是否开启Gitalk评论
 clientID: eaa2a5d08f2297528185                            #生成的clientID
 clientSecret: 88ecd13afdb33f2cbdb195c5472025311b83c853    #生成的clientSecret
 repo: SeVen7nu.github.io    #仓库名称
 owner: SeVen7nu    #github用户名
 admin: SeVen7nu
 distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·Derrick",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
